### ISSUE TITLE
Selecting Content Link Type does not populate redirect destination

### ISSUE THREAD

**Issue by jwbluemodus** [patrickdemooij9/SeoToolkit.Umbraco#110] opened 2022-09-02 02:59 UTC
Umbraco Version: 
SeoToolkit Version: 1.1.0

After setting the New Url using content, the redirect destination is not saved correctly.

Steps to reproduce:

1. Create a new redirect
2. Choose "All Sites" as the domain
3. Set from url to any value using the url option 
4. Click "Set Link" for new url
5. Select "Content" link type and select any page in the site and click submit
6. New Url displays the relative path
7. Select either status code
8. Click Submit
9. New redirect is added to list of redirects, but the "To" column indicates # regardless of the page selected

![seo_toolkit_redirects_1](https://user-images.githubusercontent.com/38888979/188049879-9609157e-9841-4584-a213-d4aeda435e6e.PNG)
![seo_toolkit_redirects_2](https://user-images.githubusercontent.com/38888979/188049880-33d6cf5e-7919-4133-9935-047d44c3fb63.PNG)
![seo_toolkit_redirects_3](https://user-images.githubusercontent.com/38888979/188049881-6253788d-50e5-4467-a9e0-b60f9c3916bd.PNG)
![seo_toolkit_redirects_4](https://user-images.githubusercontent.com/38888979/188049878-36182e1a-8787-42a2-bca3-cf85256ff639.PNG)

**Comment by patrickdemooij9** [comment] 2022-09-02 07:08
Hi @jwbluemodus,
Thank you for the report, I haven't encountered this issue yet so I'll see if I can reproduce it.
Do you have multiple languages on your site? And if so, what is your default language? It might be that the URL shown in the overview is trying to get it by using the default language instead of the correct language that you've chosen in the redirect. But if you don't have multiple languages, then that shouldn't happen anyway.

**Comment by jwbluemodus** [comment] 2022-09-02 13:57
This particular site only has one language.

Thanks,
Jen

Jen Wolke
blueModus | Solution Lead
m: +1.719.329.0924

**Comment by patrickdemooij9** [comment] 2022-09-03 13:14
I've taken another look at this as it apparently doesn't happen on the Umbraco 10 version. The issue is most likely not caused by SeoToolkit, but by a bug from within Umbraco. I can reproduce your issue on 9.1.0, but it doesn't happen on 9.5.3 anymore. I believe this is the PR that fixed the issue: https://github.com/umbraco/Umbraco-CMS/pull/11886

So I am assuming that your Umbraco version isn't up to date to include that fix. If that isn't the case, then please reopen the issue but I'll close it for now as I'll consider it a Umbraco issue.

**Closed by patrickdemooij9** 2022-09-03 13:14 UTC

**Comment by jwbluemodus** [comment] 2022-09-07 20:48
Thank you!  I will apply the latest upgrade and see if that resolves the issue.  Thanks so much for the investigation and response!

Jen Wolke
blueModus | Solution Lead
m: +1.719.329.0924
