### ISSUE TITLE
1.1.0 Not working in umbraco 9.4

### ISSUE THREAD

**Issue by trentpattern** [patrickdemooij9/SeoToolkit.Umbraco#135] opened 2022-11-29 22:50 UTC
I installed the package but get this error when going to the SEO Toolkit menu:

Received an error from the server
An error occurred

Object reference not set to an instance of an object.
Exception Details
System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.
Stacktrace

at Umbraco.Cms.Web.BackOffice.Trees.TreeControllerBase.GetNodes(String id, FormCollection queryStrings)

   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetChildren(Tree tree, Int32 id, FormCollection querystring)

   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetTreeRootNode(Tree tree, Int32 id, FormCollection querystring)

   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetApplicationTrees(String application, String tree, FormCollection queryStrings, TreeUse use)

   at lambda_method417(Closure , Object )

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by patrickdemooij9** [comment] 2022-11-30 08:57
Hi @trentpattern 
Thank you for your report. Not quite sure why this would happen, but I'll take a look at it and see what I can find. I'll keep you updated!

**Comment by patrickdemooij9** [comment] 2022-12-04 10:42
@trentpattern 
Are you sure that you are using Umbraco 9.4.0 and SeoToolkit 1.1.0? I can't reproduce this issue as I don't get an error when going to the SeoToolkit section.

**Comment by patrickdemooij9** [comment] 2023-01-11 20:16
Hi @trentpattern 
As I didn't hear back from you, I'll be closing this issue. Please let me know if you still have this issue

**Closed as completed by patrickdemooij9** 2023-01-11 20:16 UTC
